# 01-pytorch-tensors



# What is PyTorch !!?

According to their official website [https://pytorch.org/] `PyTorch` is An open source machine learning framework that accelerates the path from research prototyping to production deployment.

And when you move to their github page [https://github.com/pytorch/pytorch] you will find these points

At the core `PyTorch` is a `python` package that provides two high-level features:
* Tensor computation (like NumPy) with strong GPU acceleration
* Deep neural networks built on a tape-based autograd system

We can reuse our favorite python packages such as `NumPy`, `SciPy`, and `Cython` to extend `Pytorch` when needed

Alright, too much theory!!
Let's look at some code, later we can learn some more theory part or fundamentals

`Note : Any of these are not own words, i crawl around websites and try 
to bring the best here 🤪!! Sometimes it's harder to keep everything at one place; So I did this....[Ohho!!].`


# Tensors

As I said earlier at it's core, Pytorch is a library for processing tensors. Instead of saying blah blah blah about tensor, in simple words `tensor is just collection of numbers in specific shape (really!?) which can run on both CPU and GPU.`

or

`In the general case, an array of numbers arranged on a regular grid with a variable number of axes is known as a tensor.`
                                       - [link](https://www.amazon.com/Deep-Learning-Adaptive-Computation-Machine/dp/0262035618/ref=as_li_ss_tl?ie=UTF8&qid=1513728680&sr=8-3&keywords=deep+learning&linkCode=sl1&tag=inspiredalgor-20&linkId=b1b8f643b74f61f5074ee6dc0c993de7)
                                       
or


`A tensor is a number, vector, matrix or any n-dimensional array. `

So let's create a tensor with a single number.

In [1]:
#importing torch assuming that its already installed
import torch

In [2]:
#creating a tensor with a single number
t1 = torch.tensor(7)
t1

tensor(7)

In [3]:
#checking datatype of tensor t1
t1.dtype

torch.int64

Ummm can we create a tensor with float type !!??  YESSS!!

In [4]:
t2 = torch.tensor(7.)
t2

tensor(7.)

7. is just 7.0 don't worry!!. Let's check datatype 

In [5]:
t2.dtype

torch.float32

Ok, until now we have seen pretty simple tensors, lets make some more with more complexity..... [Oh, No..!!]

In [6]:
# vector tensor
t3 = torch.tensor([1., 2., 3., 4.])
t3

tensor([1., 2., 3., 4.])

In [7]:
# matrix array maybe(?) 2-dimensional
t4 = torch.tensor([[5., 6],
                   [7., 8.],
                   [9., 10]])
t4


tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [8]:
t4.shape

torch.Size([3, 2])

In [9]:
#3-dimensional array
t5 =  torch.tensor([
     [
       [1, 2, 3],
       [4, 5, 6]
     ],
     [
       [1, 2, 3],
       [4, 5, 6]
     ],
     [
       [1, 2, 3],
       [4, 5, 6]
     ]
   ])
t5

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])

In [10]:
t5.shape

torch.Size([3, 2, 3])

So, in the above example what its saying is a tensor with <b>3</b> layers/ depths with 2 row with 3 items. In simple words `3 two-dimensional arrays`

# Automatic Differentiation

When training neural network, as you might have heard the most frequently used algorithm is `back propagation`[really?]. The `back propagation algorithm` really requires gradient of the loss function[more about the later [but why!??😭]] 


Let's look at an example

PS: It's not my pure example I am putting here; Its from PyTorch official website. Credits are given in the end  🤷

In [11]:
#creating tensor
x = torch.tensor(7.)
w = torch.tensor(8., requires_grad=True)
b = torch.tensor(9., requires_grad=True)
x, w, b

(tensor(7.), tensor(8., requires_grad=True), tensor(9., requires_grad=True))

In [12]:
y = w * x + b
y

tensor(65., grad_fn=<AddBackward0>)

What we did was a simple arithmetic operation with the tensors that we created. It's somewhat related to ML/DL field. We can learn about it later. For now let's just see it as an arithmetic operation.
Here with the help of PyTorch we can automatically compute derivative of `y`

In [13]:
#derivaties
y.backward()

In [14]:
#Displaying gradients
print(x.grad)
#dy/dw
print(w.grad)
#dy/db
print(b.grad)

None
tensor(7.)
tensor(1.)


Here `grad` is just gradient which just another word for derivative

# Some more theory about PyTorch


🤪

Let's continue with some theory part
In `PyTorch` we can reuse our favorite Python packages such as `NumPy`, `SciPy` and `Cython` to extend PyTorch when we needed


To tell more about PyTorch :

* A GPU- Ready Tensor Library
* Dynamic Neural Networks: Tape-Based Autograd
* Python First
* Imperative Experiences
* Fast and Lean
* Extension without pain

## At granular level, PyTorch is a library that consists of the following components:



* <b>[torch](https://pytorch.org/docs/stable/torch.html)</b> :	A Tensor library like NumPy, with strong GPU support
* <b>[torch.autograd](https://pytorch.org/docs/stable/autograd.html) </b>:	A tape-based automatic differentiation library that supports all differentiable Tensor operations in torch
* <b>[torch.jit](https://pytorch.org/docs/stable/jit.html)</b>:	A compilation stack (TorchScript) to create serializable and optimizable models from PyTorch code
* <b>[torch.nn](https://pytorch.org/docs/stable/nn.html)</b>:	A neural networks library deeply integrated with autograd designed for maximum flexibility
* <b>[torch.multiprocessing](https://pytorch.org/docs/stable/multiprocessing.html)</b>:	Python multiprocessing, but with magical memory sharing of torch Tensors across processes. Useful for data loading and Hogwild training
* <b>[torch.utils](https://pytorch.org/docs/stable/data.html)</b>:	DataLoader and other utility functions for convenience



# Conclusion and credits

This is just an introduction that I have done here. More things on PyTorch will be coming soon. With all respect i am giving credits for the authors or notebooks that I have referred for this notebook/blog.

* https://github.com/pytorch/pytorch
* https://towardsdatascience.com/understanding-dimensions-in-pytorch-6edf9972d3be
* https://pytorch.org/
* https://jovian.ai/learn/deep-learning-with-pytorch-zero-to-gans/lesson/lesson-1-pytorch-basics-and-linear-regression

